/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Color = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'green' : IDL.Null,
  'black' : IDL.Null,
  'white' : IDL.Null,
  'yellow' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MatchStatus = IDL.Variant({
  'live' : IDL.Null,
  'completed' : IDL.Null,
  'setup' : IDL.Null,
});
export const BowlingStats = IDL.Record({
  'maidens' : IDL.Nat,
  'overs' : IDL.Nat,
  'runs' : IDL.Nat,
  'wickets' : IDL.Nat,
});
export const BattingStats = IDL.Record({
  'fours' : IDL.Nat,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'ballsFaced' : IDL.Nat,
  'isOut' : IDL.Bool,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'bowlingStats' : BowlingStats,
  'name' : IDL.Text,
  'battingStats' : BattingStats,
  'jerseyNumber' : IDL.Nat,
  'teamId' : IDL.Nat,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : Color,
  'players' : IDL.Vec(Player),
});
export const InningsStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
});
export const DismissalType = IDL.Variant({
  'runout' : IDL.Null,
  'hitwicket' : IDL.Null,
  'stumping' : IDL.Null,
  'bowled' : IDL.Null,
  'caught' : IDL.Null,
});
export const ExtrasType = IDL.Variant({
  'bye' : IDL.Null,
  'noball' : IDL.Null,
  'none' : IDL.Null,
  'wide' : IDL.Null,
  'legbye' : IDL.Null,
});
export const Ball = IDL.Record({
  'strikerId' : IDL.Nat,
  'ballNumber' : IDL.Nat,
  'dismissalType' : IDL.Opt(DismissalType),
  'runs' : IDL.Nat,
  'extrasType' : ExtrasType,
  'nonStrikerId' : IDL.Nat,
  'overNumber' : IDL.Nat,
  'isFreeHit' : IDL.Bool,
  'isWicket' : IDL.Bool,
  'fielderId' : IDL.Opt(IDL.Nat),
  'bowlerId' : IDL.Nat,
});
export const Over = IDL.Vec(Ball);
export const FallOfWicket = IDL.Record({
  'ball' : IDL.Nat,
  'batsmanId' : IDL.Nat,
  'over' : IDL.Nat,
  'score' : IDL.Nat,
});
export const Partnership = IDL.Record({
  'startOver' : IDL.Nat,
  'strikerId' : IDL.Nat,
  'endOver' : IDL.Nat,
  'runs' : IDL.Nat,
  'nonStrikerId' : IDL.Nat,
  'balls' : IDL.Nat,
});
export const Innings = IDL.Record({
  'status' : InningsStatus,
  'strikerId' : IDL.Nat,
  'bowlingTeamId' : IDL.Nat,
  'overs' : IDL.Vec(Over),
  'byes' : IDL.Nat,
  'legByes' : IDL.Nat,
  'totalRuns' : IDL.Nat,
  'nonStrikerId' : IDL.Nat,
  'noBalls' : IDL.Nat,
  'wicketsFallen' : IDL.Vec(FallOfWicket),
  'wickets' : IDL.Nat,
  'balls' : IDL.Vec(Ball),
  'overCount' : IDL.Nat,
  'totalBalls' : IDL.Nat,
  'currentPartnership' : IDL.Opt(Partnership),
  'isFirstInnings' : IDL.Bool,
  'extras' : IDL.Nat,
  'currentBowlerId' : IDL.Nat,
  'wides' : IDL.Nat,
  'partnerships' : IDL.Vec(Partnership),
  'battingTeamId' : IDL.Nat,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'result' : IDL.Opt(IDL.Text),
  'teams' : IDL.Vec(Team),
  'date' : Time,
  'name' : IDL.Text,
  'innings' : IDL.Vec(Innings),
  'maxOvers' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addTeam' : IDL.Func([IDL.Nat, IDL.Text, Color], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Text, Time, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Color = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'green' : IDL.Null,
    'black' : IDL.Null,
    'white' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MatchStatus = IDL.Variant({
    'live' : IDL.Null,
    'completed' : IDL.Null,
    'setup' : IDL.Null,
  });
  const BowlingStats = IDL.Record({
    'maidens' : IDL.Nat,
    'overs' : IDL.Nat,
    'runs' : IDL.Nat,
    'wickets' : IDL.Nat,
  });
  const BattingStats = IDL.Record({
    'fours' : IDL.Nat,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'ballsFaced' : IDL.Nat,
    'isOut' : IDL.Bool,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'bowlingStats' : BowlingStats,
    'name' : IDL.Text,
    'battingStats' : BattingStats,
    'jerseyNumber' : IDL.Nat,
    'teamId' : IDL.Nat,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : Color,
    'players' : IDL.Vec(Player),
  });
  const InningsStatus = IDL.Variant({
    'closed' : IDL.Null,
    'active' : IDL.Null,
  });
  const DismissalType = IDL.Variant({
    'runout' : IDL.Null,
    'hitwicket' : IDL.Null,
    'stumping' : IDL.Null,
    'bowled' : IDL.Null,
    'caught' : IDL.Null,
  });
  const ExtrasType = IDL.Variant({
    'bye' : IDL.Null,
    'noball' : IDL.Null,
    'none' : IDL.Null,
    'wide' : IDL.Null,
    'legbye' : IDL.Null,
  });
  const Ball = IDL.Record({
    'strikerId' : IDL.Nat,
    'ballNumber' : IDL.Nat,
    'dismissalType' : IDL.Opt(DismissalType),
    'runs' : IDL.Nat,
    'extrasType' : ExtrasType,
    'nonStrikerId' : IDL.Nat,
    'overNumber' : IDL.Nat,
    'isFreeHit' : IDL.Bool,
    'isWicket' : IDL.Bool,
    'fielderId' : IDL.Opt(IDL.Nat),
    'bowlerId' : IDL.Nat,
  });
  const Over = IDL.Vec(Ball);
  const FallOfWicket = IDL.Record({
    'ball' : IDL.Nat,
    'batsmanId' : IDL.Nat,
    'over' : IDL.Nat,
    'score' : IDL.Nat,
  });
  const Partnership = IDL.Record({
    'startOver' : IDL.Nat,
    'strikerId' : IDL.Nat,
    'endOver' : IDL.Nat,
    'runs' : IDL.Nat,
    'nonStrikerId' : IDL.Nat,
    'balls' : IDL.Nat,
  });
  const Innings = IDL.Record({
    'status' : InningsStatus,
    'strikerId' : IDL.Nat,
    'bowlingTeamId' : IDL.Nat,
    'overs' : IDL.Vec(Over),
    'byes' : IDL.Nat,
    'legByes' : IDL.Nat,
    'totalRuns' : IDL.Nat,
    'nonStrikerId' : IDL.Nat,
    'noBalls' : IDL.Nat,
    'wicketsFallen' : IDL.Vec(FallOfWicket),
    'wickets' : IDL.Nat,
    'balls' : IDL.Vec(Ball),
    'overCount' : IDL.Nat,
    'totalBalls' : IDL.Nat,
    'currentPartnership' : IDL.Opt(Partnership),
    'isFirstInnings' : IDL.Bool,
    'extras' : IDL.Nat,
    'currentBowlerId' : IDL.Nat,
    'wides' : IDL.Nat,
    'partnerships' : IDL.Vec(Partnership),
    'battingTeamId' : IDL.Nat,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'result' : IDL.Opt(IDL.Text),
    'teams' : IDL.Vec(Team),
    'date' : Time,
    'name' : IDL.Text,
    'innings' : IDL.Vec(Innings),
    'maxOvers' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addTeam' : IDL.Func([IDL.Nat, IDL.Text, Color], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([IDL.Text, Time, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };