/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Ball {
  'strikerId' : bigint,
  'ballNumber' : bigint,
  'dismissalType' : [] | [DismissalType],
  'runs' : bigint,
  'extrasType' : ExtrasType,
  'nonStrikerId' : bigint,
  'overNumber' : bigint,
  'isFreeHit' : boolean,
  'isWicket' : boolean,
  'fielderId' : [] | [bigint],
  'bowlerId' : bigint,
}
export interface BattingStats {
  'fours' : bigint,
  'runs' : bigint,
  'sixes' : bigint,
  'ballsFaced' : bigint,
  'isOut' : boolean,
}
export interface BowlingStats {
  'maidens' : bigint,
  'overs' : bigint,
  'runs' : bigint,
  'wickets' : bigint,
}
export type Color = { 'red' : null } |
  { 'blue' : null } |
  { 'green' : null } |
  { 'black' : null } |
  { 'white' : null } |
  { 'yellow' : null };
export type DismissalType = { 'runout' : null } |
  { 'hitwicket' : null } |
  { 'stumping' : null } |
  { 'bowled' : null } |
  { 'caught' : null };
export type ExtrasType = { 'bye' : null } |
  { 'noball' : null } |
  { 'none' : null } |
  { 'wide' : null } |
  { 'legbye' : null };
export interface FallOfWicket {
  'ball' : bigint,
  'batsmanId' : bigint,
  'over' : bigint,
  'score' : bigint,
}
export interface Innings {
  'status' : InningsStatus,
  'strikerId' : bigint,
  'bowlingTeamId' : bigint,
  'overs' : Array<Over>,
  'byes' : bigint,
  'legByes' : bigint,
  'totalRuns' : bigint,
  'nonStrikerId' : bigint,
  'noBalls' : bigint,
  'wicketsFallen' : Array<FallOfWicket>,
  'wickets' : bigint,
  'balls' : Array<Ball>,
  'overCount' : bigint,
  'totalBalls' : bigint,
  'currentPartnership' : [] | [Partnership],
  'isFirstInnings' : boolean,
  'extras' : bigint,
  'currentBowlerId' : bigint,
  'wides' : bigint,
  'partnerships' : Array<Partnership>,
  'battingTeamId' : bigint,
}
export type InningsStatus = { 'closed' : null } |
  { 'active' : null };
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'result' : [] | [string],
  'teams' : Array<Team>,
  'date' : Time,
  'name' : string,
  'innings' : Array<Innings>,
  'maxOvers' : [] | [bigint],
}
export type MatchStatus = { 'live' : null } |
  { 'completed' : null } |
  { 'setup' : null };
export type Over = Array<Ball>;
export interface Partnership {
  'startOver' : bigint,
  'strikerId' : bigint,
  'endOver' : bigint,
  'runs' : bigint,
  'nonStrikerId' : bigint,
  'balls' : bigint,
}
export interface Player {
  'id' : bigint,
  'bowlingStats' : BowlingStats,
  'name' : string,
  'battingStats' : BattingStats,
  'jerseyNumber' : bigint,
  'teamId' : bigint,
}
export interface Team {
  'id' : bigint,
  'name' : string,
  'color' : Color,
  'players' : Array<Player>,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[bigint, bigint, string, bigint], bigint>,
  'addTeam' : ActorMethod<[bigint, string, Color], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[string, Time, [] | [bigint]], bigint>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[bigint], Match>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMatches' : ActorMethod<[], Array<Match>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];