/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BattingStats {
  'fours' : bigint,
  'runs' : bigint,
  'sixes' : bigint,
  'ballsFaced' : bigint,
  'isOut' : boolean,
}
export interface BowlingStats {
  'maidens' : bigint,
  'overs' : bigint,
  'runs' : bigint,
  'wickets' : bigint,
}
export type Color = { 'red' : null } |
  { 'blue' : null } |
  { 'green' : null } |
  { 'black' : null } |
  { 'white' : null } |
  { 'yellow' : null };
export interface Innings {
  'result' : [] | [string],
  'bowlingTeamId' : bigint,
  'byes' : bigint,
  'legByes' : bigint,
  'totalRuns' : bigint,
  'noBalls' : bigint,
  'legalBalls' : bigint,
  'wickets' : bigint,
  'isFirstInnings' : boolean,
  'wides' : bigint,
  'battingTeamId' : bigint,
}
export interface Match {
  'id' : bigint,
  'status' : MatchStatus,
  'result' : [] | [string],
  'teams' : Array<Team>,
  'date' : Time,
  'name' : string,
  'innings' : Array<Innings>,
  'maxOvers' : [] | [bigint],
}
export type MatchStatus = { 'live' : null } |
  { 'completed' : null } |
  { 'setup' : null };
export interface Player {
  'id' : bigint,
  'bowlingStats' : BowlingStats,
  'name' : string,
  'battingStats' : BattingStats,
  'jerseyNumber' : bigint,
  'teamId' : bigint,
}
export interface PlayerAggregateStats {
  'totalFours' : bigint,
  'totalMatches' : bigint,
  'totalWickets' : bigint,
  'totalRuns' : bigint,
  'totalSixes' : bigint,
  'totalOversBowled' : bigint,
  'totalBalls' : bigint,
  'totalRunsConceded' : bigint,
}
export interface Team {
  'id' : bigint,
  'name' : string,
  'color' : Color,
  'players' : Array<Player>,
}
export interface TeamAggregateStats {
  'totalWicketsTaken' : bigint,
  'totalMatches' : bigint,
  'wins' : bigint,
  'losses' : bigint,
  'totalRunsScored' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlayer' : ActorMethod<[bigint, bigint, string, bigint], bigint>,
  'addTeam' : ActorMethod<[bigint, string, Color], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMatch' : ActorMethod<[string, Time, [] | [bigint]], bigint>,
  'deleteMatch' : ActorMethod<[bigint], undefined>,
  'getAllTeamStats' : ActorMethod<[], Array<[string, TeamAggregateStats]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMatch' : ActorMethod<[bigint], Match>,
  'getPlayerAggregateStats' : ActorMethod<
    [bigint],
    [] | [PlayerAggregateStats]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMatches' : ActorMethod<[], Array<Match>>,
  'rematch' : ActorMethod<[bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveInningsResult' : ActorMethod<
    [
      bigint,
      boolean,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      bigint,
      [] | [string],
    ],
    undefined
  >,
  'savePlayerStats' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'saveTeamStats' : ActorMethod<[string, boolean, bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];