/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Color = IDL.Variant({
  'red' : IDL.Null,
  'blue' : IDL.Null,
  'green' : IDL.Null,
  'black' : IDL.Null,
  'white' : IDL.Null,
  'yellow' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const TeamAggregateStats = IDL.Record({
  'totalWicketsTaken' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'wins' : IDL.Nat,
  'losses' : IDL.Nat,
  'totalRunsScored' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const MatchStatus = IDL.Variant({
  'live' : IDL.Null,
  'completed' : IDL.Null,
  'setup' : IDL.Null,
});
export const BowlingStats = IDL.Record({
  'maidens' : IDL.Nat,
  'overs' : IDL.Nat,
  'runs' : IDL.Nat,
  'wickets' : IDL.Nat,
});
export const BattingStats = IDL.Record({
  'fours' : IDL.Nat,
  'runs' : IDL.Nat,
  'sixes' : IDL.Nat,
  'ballsFaced' : IDL.Nat,
  'isOut' : IDL.Bool,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'bowlingStats' : BowlingStats,
  'name' : IDL.Text,
  'battingStats' : BattingStats,
  'jerseyNumber' : IDL.Nat,
  'teamId' : IDL.Nat,
});
export const Team = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : Color,
  'players' : IDL.Vec(Player),
});
export const Innings = IDL.Record({
  'result' : IDL.Opt(IDL.Text),
  'bowlingTeamId' : IDL.Nat,
  'byes' : IDL.Nat,
  'legByes' : IDL.Nat,
  'totalRuns' : IDL.Nat,
  'noBalls' : IDL.Nat,
  'legalBalls' : IDL.Nat,
  'wickets' : IDL.Nat,
  'isFirstInnings' : IDL.Bool,
  'wides' : IDL.Nat,
  'battingTeamId' : IDL.Nat,
});
export const Match = IDL.Record({
  'id' : IDL.Nat,
  'status' : MatchStatus,
  'result' : IDL.Opt(IDL.Text),
  'teams' : IDL.Vec(Team),
  'date' : Time,
  'name' : IDL.Text,
  'innings' : IDL.Vec(Innings),
  'maxOvers' : IDL.Opt(IDL.Nat),
});
export const PlayerAggregateStats = IDL.Record({
  'totalFours' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'totalWickets' : IDL.Nat,
  'totalRuns' : IDL.Nat,
  'totalSixes' : IDL.Nat,
  'totalOversBowled' : IDL.Nat,
  'totalBalls' : IDL.Nat,
  'totalRunsConceded' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlayer' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'addTeam' : IDL.Func([IDL.Nat, IDL.Text, Color], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMatch' : IDL.Func([IDL.Text, Time, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
  'deleteMatch' : IDL.Func([IDL.Nat], [], []),
  'getAllTeamStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, TeamAggregateStats))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
  'getPlayerAggregateStats' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(PlayerAggregateStats)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
  'rematch' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveInningsResult' : IDL.Func(
      [
        IDL.Nat,
        IDL.Bool,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'savePlayerStats' : IDL.Func(
      [
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'saveTeamStats' : IDL.Func([IDL.Text, IDL.Bool, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Color = IDL.Variant({
    'red' : IDL.Null,
    'blue' : IDL.Null,
    'green' : IDL.Null,
    'black' : IDL.Null,
    'white' : IDL.Null,
    'yellow' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const TeamAggregateStats = IDL.Record({
    'totalWicketsTaken' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'wins' : IDL.Nat,
    'losses' : IDL.Nat,
    'totalRunsScored' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const MatchStatus = IDL.Variant({
    'live' : IDL.Null,
    'completed' : IDL.Null,
    'setup' : IDL.Null,
  });
  const BowlingStats = IDL.Record({
    'maidens' : IDL.Nat,
    'overs' : IDL.Nat,
    'runs' : IDL.Nat,
    'wickets' : IDL.Nat,
  });
  const BattingStats = IDL.Record({
    'fours' : IDL.Nat,
    'runs' : IDL.Nat,
    'sixes' : IDL.Nat,
    'ballsFaced' : IDL.Nat,
    'isOut' : IDL.Bool,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'bowlingStats' : BowlingStats,
    'name' : IDL.Text,
    'battingStats' : BattingStats,
    'jerseyNumber' : IDL.Nat,
    'teamId' : IDL.Nat,
  });
  const Team = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : Color,
    'players' : IDL.Vec(Player),
  });
  const Innings = IDL.Record({
    'result' : IDL.Opt(IDL.Text),
    'bowlingTeamId' : IDL.Nat,
    'byes' : IDL.Nat,
    'legByes' : IDL.Nat,
    'totalRuns' : IDL.Nat,
    'noBalls' : IDL.Nat,
    'legalBalls' : IDL.Nat,
    'wickets' : IDL.Nat,
    'isFirstInnings' : IDL.Bool,
    'wides' : IDL.Nat,
    'battingTeamId' : IDL.Nat,
  });
  const Match = IDL.Record({
    'id' : IDL.Nat,
    'status' : MatchStatus,
    'result' : IDL.Opt(IDL.Text),
    'teams' : IDL.Vec(Team),
    'date' : Time,
    'name' : IDL.Text,
    'innings' : IDL.Vec(Innings),
    'maxOvers' : IDL.Opt(IDL.Nat),
  });
  const PlayerAggregateStats = IDL.Record({
    'totalFours' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'totalWickets' : IDL.Nat,
    'totalRuns' : IDL.Nat,
    'totalSixes' : IDL.Nat,
    'totalOversBowled' : IDL.Nat,
    'totalBalls' : IDL.Nat,
    'totalRunsConceded' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlayer' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addTeam' : IDL.Func([IDL.Nat, IDL.Text, Color], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMatch' : IDL.Func([IDL.Text, Time, IDL.Opt(IDL.Nat)], [IDL.Nat], []),
    'deleteMatch' : IDL.Func([IDL.Nat], [], []),
    'getAllTeamStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, TeamAggregateStats))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMatch' : IDL.Func([IDL.Nat], [Match], ['query']),
    'getPlayerAggregateStats' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PlayerAggregateStats)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMatches' : IDL.Func([], [IDL.Vec(Match)], ['query']),
    'rematch' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveInningsResult' : IDL.Func(
        [
          IDL.Nat,
          IDL.Bool,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'savePlayerStats' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'saveTeamStats' : IDL.Func([IDL.Text, IDL.Bool, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };