/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Player {
    id: bigint;
    bowlingStats: BowlingStats;
    name: string;
    battingStats: BattingStats;
    jerseyNumber: bigint;
    teamId: bigint;
}
export type Time = bigint;
export interface Innings {
    result?: string;
    bowlingTeamId: bigint;
    byes: bigint;
    legByes: bigint;
    totalRuns: bigint;
    noBalls: bigint;
    legalBalls: bigint;
    wickets: bigint;
    isFirstInnings: boolean;
    wides: bigint;
    battingTeamId: bigint;
}
export interface BowlingStats {
    maidens: bigint;
    overs: bigint;
    runs: bigint;
    wickets: bigint;
}
export interface BattingStats {
    fours: bigint;
    runs: bigint;
    sixes: bigint;
    ballsFaced: bigint;
    isOut: boolean;
}
export interface Match {
    id: bigint;
    status: MatchStatus;
    result?: string;
    teams: Array<Team>;
    date: Time;
    name: string;
    innings: Array<Innings>;
    maxOvers?: bigint;
}
export interface UserProfile {
    name: string;
}
export interface Team {
    id: bigint;
    name: string;
    color: Color;
    players: Array<Player>;
}
export enum Color {
    red = "red",
    blue = "blue",
    green = "green",
    black = "black",
    white = "white",
    yellow = "yellow"
}
export enum MatchStatus {
    live = "live",
    completed = "completed",
    setup = "setup"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPlayer(matchId: bigint, teamId: bigint, playerName: string, jerseyNumber: bigint): Promise<bigint>;
    addTeam(matchId: bigint, teamName: string, color: Color): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMatch(name: string, date: Time, maxOvers: bigint | null): Promise<bigint>;
    deleteMatch(matchId: bigint): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMatch(matchId: bigint): Promise<Match>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listMatches(): Promise<Array<Match>>;
    rematch(matchId: bigint): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveInningsResult(matchId: bigint, isFirstInnings: boolean, battingTeamId: bigint, bowlingTeamId: bigint, totalRuns: bigint, wickets: bigint, legalBalls: bigint, wides: bigint, noBalls: bigint, byes: bigint, legByes: bigint, result: string | null): Promise<void>;
}
import type { Color as _Color, Innings as _Innings, Match as _Match, MatchStatus as _MatchStatus, Player as _Player, Team as _Team, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPlayer(arg0: bigint, arg1: bigint, arg2: string, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPlayer(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addTeam(arg0: bigint, arg1: string, arg2: Color): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addTeam(arg0, arg1, to_candid_Color_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTeam(arg0, arg1, to_candid_Color_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMatch(arg0: string, arg1: Time, arg2: bigint | null): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async deleteMatch(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMatch(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatch(arg0: bigint): Promise<Match> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_Match_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_Match_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMatches(): Promise<Array<Match>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMatches();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMatches();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async rematch(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.rematch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rematch(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveInningsResult(arg0: bigint, arg1: boolean, arg2: bigint, arg3: bigint, arg4: bigint, arg5: bigint, arg6: bigint, arg7: bigint, arg8: bigint, arg9: bigint, arg10: bigint, arg11: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveInningsResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveInningsResult(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n24(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
}
function from_candid_Color_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Color): Color {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Innings_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Innings): Innings {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_MatchStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MatchStatus): MatchStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Match_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Match): Match {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Team_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Team): Team {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MatchStatus;
    result: [] | [string];
    teams: Array<_Team>;
    date: _Time;
    name: string;
    innings: Array<_Innings>;
    maxOvers: [] | [bigint];
}): {
    id: bigint;
    status: MatchStatus;
    result?: string;
    teams: Array<Team>;
    date: Time;
    name: string;
    innings: Array<Innings>;
    maxOvers?: bigint;
} {
    return {
        id: value.id,
        status: from_candid_MatchStatus_n11(_uploadFile, _downloadFile, value.status),
        result: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.result)),
        teams: from_candid_vec_n14(_uploadFile, _downloadFile, value.teams),
        date: value.date,
        name: value.name,
        innings: from_candid_vec_n19(_uploadFile, _downloadFile, value.innings),
        maxOvers: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.maxOvers))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    color: _Color;
    players: Array<_Player>;
}): {
    id: bigint;
    name: string;
    color: Color;
    players: Array<Player>;
} {
    return {
        id: value.id,
        name: value.name,
        color: from_candid_Color_n17(_uploadFile, _downloadFile, value.color),
        players: value.players
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: [] | [string];
    bowlingTeamId: bigint;
    byes: bigint;
    legByes: bigint;
    totalRuns: bigint;
    noBalls: bigint;
    legalBalls: bigint;
    wickets: bigint;
    isFirstInnings: boolean;
    wides: bigint;
    battingTeamId: bigint;
}): {
    result?: string;
    bowlingTeamId: bigint;
    byes: bigint;
    legByes: bigint;
    totalRuns: bigint;
    noBalls: bigint;
    legalBalls: bigint;
    wickets: bigint;
    isFirstInnings: boolean;
    wides: bigint;
    battingTeamId: bigint;
} {
    return {
        result: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.result)),
        bowlingTeamId: value.bowlingTeamId,
        byes: value.byes,
        legByes: value.legByes,
        totalRuns: value.totalRuns,
        noBalls: value.noBalls,
        legalBalls: value.legalBalls,
        wickets: value.wickets,
        isFirstInnings: value.isFirstInnings,
        wides: value.wides,
        battingTeamId: value.battingTeamId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    live: null;
} | {
    completed: null;
} | {
    setup: null;
}): MatchStatus {
    return "live" in value ? MatchStatus.live : "completed" in value ? MatchStatus.completed : "setup" in value ? MatchStatus.setup : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    red: null;
} | {
    blue: null;
} | {
    green: null;
} | {
    black: null;
} | {
    white: null;
} | {
    yellow: null;
}): Color {
    return "red" in value ? Color.red : "blue" in value ? Color.blue : "green" in value ? Color.green : "black" in value ? Color.black : "white" in value ? Color.white : "yellow" in value ? Color.yellow : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Team>): Array<Team> {
    return value.map((x)=>from_candid_Team_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Innings>): Array<Innings> {
    return value.map((x)=>from_candid_Innings_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Match>): Array<Match> {
    return value.map((x)=>from_candid_Match_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Color_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): _Color {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Color): {
    red: null;
} | {
    blue: null;
} | {
    green: null;
} | {
    black: null;
} | {
    white: null;
} | {
    yellow: null;
} {
    return value == Color.red ? {
        red: null
    } : value == Color.blue ? {
        blue: null
    } : value == Color.green ? {
        green: null
    } : value == Color.black ? {
        black: null
    } : value == Color.white ? {
        white: null
    } : value == Color.yellow ? {
        yellow: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
